(()=>{'use strict';
const cfg=window.CHANANYA_AUTH||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const url=cfg.supabaseUrl||cfg.url,key=cfg.publishableKey||cfg.anonKey||cfg.key;
let db,session,systemRole='staff',operationalRole='viewer';
let data={tasks:[],actions:[],users:[],summary:{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function fail(e){console.error(e);alert(e?.message||String(e))}
async function q(t,s='*',order){let r=db.from(t).select(s);if(order)r=r.order(order,{ascending:false});const x=await r;if(x.error)throw x.error;return x.data||[]}
async function load(){const [tasks,actions,users,summaryRows]=await Promise.all([
  q('approval_tasks','*','requested_at'),q('approval_actions','*','acted_at'),q('user_access_summary'),q('admin_task_summary')
]);data={tasks,actions,users,summary:summaryRows[0]||{}};render()}
function opts(arr,label){return '<option value="">เลือก</option>'+arr.map(x=>`<option value="${x.id}">${esc(label(x))}</option>`).join('')}
function render(){const s=data.summary;$('#stat-pending').textContent=s.pending||0;$('#stat-review').textContent=s.in_review||0;$('#stat-urgent').textContent=s.urgent||0;$('#stat-overdue').textContent=s.overdue||0;$('#stat-approved').textContent=s.approved_today||0;
 const userOptions=opts(data.users,u=>`${u.full_name||u.id} — ${u.effective_role||u.role}`);$('#staff-user').innerHTML=userOptions;$('#system-user').innerHTML=userOptions;
 $('#super-admin-card').classList.toggle('hidden',systemRole!=='super_admin');renderTasks();renderUsers();renderActions()}
function renderTasks(){const active=data.tasks.filter(t=>['pending','in_review'].includes(t.status));$('#task-list').innerHTML=active.map(t=>{const b=[];if(t.status==='pending')b.push(`<button class="btn ghost" data-act="take" data-id="${t.id}">รับตรวจ</button>`);b.push(`<button class="btn primary" data-act="approve" data-id="${t.id}">อนุมัติ</button><button class="btn danger" data-act="reject" data-id="${t.id}">ปฏิเสธ</button>`);return `<div class="item column"><div class="wide"><div class="row"><b>${esc(t.task_no)} • ${esc(t.title)}</b><span class="badge">${esc(t.priority)} / ${esc(t.status)}</span></div><small>${esc(t.module)} • ${esc(t.task_type)} • ${new Date(t.requested_at).toLocaleString('th-TH')}</small><p>${esc(t.description||'')}</p><div class="right">${b.join('')}</div></div></div>`}).join('')||'<p class="muted">ไม่มีงานรออนุมัติ</p>';bindActions()}
function renderUsers(){$('#user-list').innerHTML=data.users.map(u=>`<div class="item"><div><b>${esc(u.full_name||u.id)}</b><small>Operational: ${esc(u.role)} • System: ${esc(u.system_role)} • Effective: ${esc(u.effective_role)}</small></div><span class="badge">${esc(u.effective_role)}</span></div>`).join('')||'<p class="muted">ไม่พบผู้ใช้</p>'}
function renderActions(){$('#action-list').innerHTML=data.actions.map(a=>`<div class="item"><div><b>${esc(a.action)} • ${esc(a.from_status||'-')} → ${esc(a.to_status||'-')}</b><small>${new Date(a.acted_at).toLocaleString('th-TH')} • ${esc(a.notes||'')}</small></div></div>`).join('')||'<p class="muted">ยังไม่มีประวัติ</p>'}
function bindActions(){$$('[data-act]').forEach(b=>b.onclick=()=>decide(b.dataset.id,b.dataset.act).catch(fail))}
async function decide(id,action){const notes=prompt('หมายเหตุการตัดสินใจ','')??'';const r=await db.rpc('decide_approval_task',{p_task_id:id,p_action:action,p_notes:notes});if(r.error)throw r.error;await load();toast('บันทึกการตัดสินใจแล้ว')}
async function saveTask(e){e.preventDefault();const due=$('#task-due').value;const r=await db.rpc('create_approval_task',{p_task_type:$('#task-type').value.trim(),p_module:$('#task-module').value,p_title:$('#task-title').value.trim(),p_description:$('#task-description').value.trim()||null,p_priority:$('#task-priority').value,p_reference_type:null,p_reference_id:null,p_due_at:due?new Date(due).toISOString():null,p_metadata:{source:'admin_task_center'}});if(r.error)throw r.error;e.target.reset();await load();toast('สร้าง Task แล้ว')}
async function saveStaffRole(e){e.preventDefault();const r=await db.rpc('admin_assign_staff_role',{p_user_id:$('#staff-user').value,p_role:$('#staff-role').value,p_reason:$('#staff-reason').value.trim()||null});if(r.error)throw r.error;e.target.reset();await load();toast('บันทึก Role แล้ว')}
async function saveSystemRole(e){e.preventDefault();const r=await db.rpc('super_admin_set_system_role',{p_user_id:$('#system-user').value,p_system_role:$('#system-role').value,p_reason:$('#system-reason').value.trim()||null});if(r.error)throw r.error;e.target.reset();await load();toast('บันทึก System Role แล้ว')}
async function init(){try{if(!url||!key)throw new Error('ไม่พบ Supabase config');db=supabase.createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true}});const s=await db.auth.getSession();session=s.data.session;if(!session){location.replace('login.html');return}const p=await db.from('profiles').select('role,system_role,full_name').eq('id',session.user.id).single();if(p.error)throw p.error;systemRole=p.data.system_role||'staff';operationalRole=p.data.role||'viewer';if(!['admin','super_admin'].includes(systemRole))throw new Error('บัญชีนี้ไม่มีสิทธิ์ Admin Task Center');$('#identity').textContent=`${p.data.full_name||session.user.email} • ${session.user.email}`;$('#role').textContent=systemRole;$('#app').classList.remove('hidden');$('#boot').classList.add('hidden');await load()}catch(e){console.error(e);$('#boot-error').textContent=e.message}}
$('#admin-nav').onclick=e=>{const b=e.target.closest('button[data-view]');if(!b)return;$$('#admin-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))};
$('#task-form').addEventListener('submit',e=>saveTask(e).catch(fail));$('#staff-role-form').addEventListener('submit',e=>saveStaffRole(e).catch(fail));$('#system-role-form').addEventListener('submit',e=>saveSystemRole(e).catch(fail));$('#logout').onclick=async()=>{await db.auth.signOut();location.replace('login.html')};init();
})();