(() => {
'use strict';
const cfg=window.CHANANYA_AUTH||{};
const STATE_ID='00000000-0000-0000-0000-000000000001';
const LOCK_MS=15*60*1000;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let db,session,role='viewer',lockTimer;
let state={patients:[],appointments:[],encounters:[],inventory:[],activity:[]};
const perms={admin:['patients','appointments','clinical','inventory','delete','audit'],practitioner:['patients','appointments','clinical'],reception:['patients','appointments'],inventory:['inventory'],viewer:[]};
const can=x=>(perms[role]||[]).includes(x);
const uid=()=>crypto.randomUUID();
const today=()=>new Date().toISOString().slice(0,10);
const pname=id=>state.patients.find(p=>p.id===id)?.name||'-';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function ensure(x){if(can(x))return true;alert('บัญชีนี้ไม่มีสิทธิ์ดำเนินการ');return false}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function audit(action,entity,entityId,metadata={}){if(!session)return;await db.from('audit_logs').insert({user_id:session.user.id,action,entity,entity_id:entityId||null,metadata:{...metadata,role}})}
async function save(action='update',entity='clinic_state',entityId=STATE_ID){const payload={id:STATE_ID,data:state,updated_by:session.user.id,updated_at:new Date().toISOString()};const {error}=await db.from('clinic_state').upsert(payload);if(error)throw error;await audit(action,entity,entityId);render();toast('บันทึกแล้ว')}
async function loadData(){const p=await db.from('profiles').select('role,email,full_name').eq('id',session.user.id).single();if(p.error)throw p.error;role=p.data.role||'viewer';$('#role').textContent=role;$('#identity').textContent=session.user.email||p.data.email||'';const r=await db.from('clinic_state').select('data').eq('id',STATE_ID).maybeSingle();if(r.error)throw r.error;if(r.data?.data)state=Object.assign(state,r.data.data);else if(role!=='viewer')await db.from('clinic_state').insert({id:STATE_ID,data:state,updated_by:session.user.id});render();await audit('login','session',session.user.id)}
function render(){const patientOptions='<option value="">เลือกผู้รับบริการ</option>'+state.patients.map(p=>`<option value="${p.id}">${escapeHtml(p.hn)} — ${escapeHtml(p.name)}</option>`).join('');$('#appt-patient').innerHTML=patientOptions;$('#enc-patient').innerHTML=patientOptions;$('#stat-p').textContent=state.patients.length;$('#stat-a').textContent=state.appointments.filter(a=>a.date===today()).length;$('#stat-e').textContent=state.encounters.length;$('#stat-x').textContent=state.patients.filter(p=>p.allergy).length;$('#stat-i').textContent=state.inventory.filter(i=>i.exp&&i.exp<=today()).length;$('#patient-list').innerHTML=state.patients.map(p=>`<div class="item"><div><b>${escapeHtml(p.hn)} ${escapeHtml(p.name)}</b><small>${escapeHtml(p.phone||'-')} ${p.allergy?'• '+escapeHtml(p.allergy):''}</small></div><div class="right"><button class="btn ghost" data-edit-p="${p.id}">แก้ไข</button><button class="btn danger" data-del="patients:${p.id}">ลบ</button></div></div>`).join('')||'<p class="muted">ยังไม่มีข้อมูล</p>';$('#appointment-list').innerHTML=state.appointments.map(a=>`<div class="item"><div><b>${a.date} ${a.time}</b><small>${escapeHtml(pname(a.patientId))} • ${escapeHtml(a.service)}</small></div><button class="btn danger" data-del="appointments:${a.id}">ลบ</button></div>`).join('')||'<p class="muted">ยังไม่มีนัด</p>';$('#inventory-list').innerHTML=state.inventory.map(i=>`<div class="item"><div><b>${escapeHtml(i.name)}</b><small>Lot ${escapeHtml(i.lot)} • Exp ${escapeHtml(i.exp||'-')}</small></div><div class="right"><span class="badge">${Number(i.qty||0)}</span><button class="btn danger" data-del="inventory:${i.id}">ลบ</button></div></div>`).join('')||'<p class="muted">ยังไม่มีสต็อก</p>';$('#recent-list').innerHTML=state.encounters.slice(0,8).map(e=>`<div class="item"><div><b>${escapeHtml(pname(e.patientId))}</b><small>${escapeHtml(e.diagnosis||e.chief||'')}</small></div><span class="badge">${Number(e.before||0)}→${Number(e.after||0)}</span></div>`).join('')||'<p class="muted">ยังไม่มีประวัติ</p>';bindDynamic()}
function bindDynamic(){$$('[data-edit-p]').forEach(b=>b.onclick=()=>editPatient(b.dataset.editP));$$('[data-del]').forEach(b=>b.onclick=()=>{const [k,id]=b.dataset.del.split(':');removeItem(k,id)})}
function editPatient(id){if(!ensure('patients'))return;const p=state.patients.find(x=>x.id===id);if(!p)return;$('#p-id').value=p.id;$('#p-hn').value=p.hn;$('#p-name').value=p.name;$('#p-phone').value=p.phone||'';$('#p-dob').value=p.dob||'';$('#p-address').value=p.address||'';$('#p-allergy').value=p.allergy||'';location.hash='patients'}
async function removeItem(k,id){if(!ensure('delete'))return;if(!confirm('ยืนยันการลบข้อมูล?'))return;state[k]=state[k].filter(x=>x.id!==id);await save('delete',k,id)}
function resetLock(){clearTimeout(lockTimer);lockTimer=setTimeout(async()=>{$('#lock').classList.add('show');await audit('auto_lock','session',session.user.id)},LOCK_MS)}
async function loadAudit(){if(!can('audit')){$('#audit-list').innerHTML='<p class="error">ไม่มีสิทธิ์ดู Audit log</p>';return}const r=await db.from('audit_logs').select('*').order('occurred_at',{ascending:false}).limit(100);$('#audit-list').innerHTML=r.error?`<p class="error">${escapeHtml(r.error.message)}</p>`:r.data.map(x=>`<div class="item audit-item"><div><b>${escapeHtml(x.action)} • ${escapeHtml(x.entity)}</b><small>${new Date(x.occurred_at).toLocaleString('th-TH')} • ${escapeHtml(x.user_id||'')}</small></div></div>`).join('')}
function setupUI(){$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));if(b.dataset.view==='audit')loadAudit()});$$('.step').forEach(b=>b.onclick=()=>showStep(Number(b.dataset.step)));$('#prev-step').onclick=()=>showStep(Math.max(1,currentStep()-1));$('#next-step').onclick=()=>showStep(Math.min(5,currentStep()+1));$('#patient-form').onsubmit=savePatient;$('#appointment-form').onsubmit=saveAppointment;$('#inventory-form').onsubmit=saveInventory;$('#encounter-form').onsubmit=saveEncounter;$('#logout').onclick=async()=>{await audit('logout','session',session.user.id);await db.auth.signOut({scope:'local'});location.replace('/login-v3.html')};$('#unlock').onclick=()=>{$('#lock').classList.remove('show');resetLock()};['pointerdown','keydown','touchstart','scroll'].forEach(e=>document.addEventListener(e,()=>{if(session&&!$('#lock').classList.contains('show'))resetLock()},{passive:true}));$('#appt-date').value=today()}
function currentStep(){return Number($('.step.active')?.dataset.step||1)}
function showStep(n){$$('.step').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===n));$$('.step-panel').forEach(p=>p.classList.toggle('active',Number(p.dataset.panel)===n))}
async function savePatient(e){e.preventDefault();if(!ensure('patients'))return;const id=$('#p-id').value||uid();const x={id,hn:$('#p-hn').value.trim(),name:$('#p-name').value.trim(),phone:$('#p-phone').value.trim(),dob:$('#p-dob').value,address:$('#p-address').value.trim(),allergy:$('#p-allergy').value.trim()};const i=state.patients.findIndex(p=>p.id===id);if(i<0)state.patients.unshift(x);else state.patients[i]=x;e.target.reset();$('#p-id').value='';await save(i<0?'create':'update','patients',id)}
async function saveAppointment(e){e.preventDefault();if(!ensure('appointments'))return;const x={id:uid(),patientId:$('#appt-patient').value,date:$('#appt-date').value,time:$('#appt-time').value,service:$('#appt-service').value,practitioner:$('#appt-practitioner').value,room:$('#appt-room').value,note:$('#appt-note').value};state.appointments.unshift(x);e.target.reset();$('#appt-date').value=today();await save('create','appointments',x.id)}
async function saveInventory(e){e.preventDefault();if(!ensure('inventory'))return;const x={id:uid(),name:$('#inv-name').value,lot:$('#inv-lot').value,exp:$('#inv-exp').value,qty:Number($('#inv-qty').value||0),supplier:$('#inv-supplier').value};state.inventory.unshift(x);e.target.reset();await save('create','inventory',x.id)}
async function saveEncounter(e){e.preventDefault();if(!ensure('clinical'))return;const x={id:uid(),patientId:$('#enc-patient').value,date:new Date().toISOString(),chief:$('#enc-chief').value,history:$('#enc-history').value,medication:$('#enc-med').value,temp:$('#enc-temp').value,pulse:$('#enc-pulse').value,rr:$('#enc-rr').value,bp:$('#enc-bp').value,spo2:$('#enc-spo2').value,before:Number($('#enc-before').value||0),redflags:$('#enc-redflags').value,exam:$('#enc-exam').value,element:$('#enc-element').value,season:$('#enc-season').value,diagnosis:$('#enc-diagnosis').value,treatment:$('#enc-treatment').value,herbal:$('#enc-herbal').value,after:Number($('#enc-after').value||0),outcome:$('#enc-outcome').value,advice:$('#enc-advice').value,next:$('#enc-next').value,practitioner:$('#enc-practitioner').value};state.encounters.unshift(x);e.target.reset();showStep(1);await save('create','encounters',x.id)}
async function init(){try{if(!cfg.supabaseUrl||!cfg.publishableKey)throw new Error('Missing Supabase configuration');db=supabase.createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data,error}=await db.auth.getSession();if(error)throw error;session=data.session;if(!session){location.replace('/login-v3.html');return}await loadData();setupUI();$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');resetLock()}catch(e){$('#boot-title').textContent='เปิดระบบไม่สำเร็จ';$('#boot-error').textContent=e.message}}
document.addEventListener('DOMContentLoaded',init);
})();