(()=>{'use strict';
const cfg=window.CHANANYA_AUTH||{},LOCK_MS=15*60*1000,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let db,session,role='viewer',lockTimer;
let data={patients:[],allergies:[],appointments:[],services:[],encounters:[],products:[],lots:[],prescriptions:[],rxItems:[],dispensing:[],invoices:[],invoiceItems:[],payments:[]};
const roles={admin:['all'],practitioner:['patients','appointments','clinical','prescription'],reception:['patients','appointments'],pharmacy:['pharmacy','inventory'],inventory:['inventory'],billing:['billing'],viewer:[]};
const can=x=>(roles[role]||[]).includes('all')||(roles[role]||[]).includes(x),today=()=>new Date().toISOString().slice(0,10),uid=()=>crypto.randomUUID();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(v||0),money=v=>num(v).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function requireRole(x){if(can(x))return true;alert('บัญชีนี้ไม่มีสิทธิ์ดำเนินการ');return false}
function patientName(id){const p=data.patients.find(x=>x.id===id);return p?`${p.prefix||''}${p.first_name} ${p.last_name}`:'-'}
function encounterLabel(e){return `${e.encounter_no} • ${patientName(e.patient_id)}`}
async function audit(action,entity,entityId,metadata={}){try{await db.from('audit_logs').insert({user_id:session.user.id,action,entity,entity_id:entityId||null,metadata:{...metadata,role}})}catch(_){}}
async function q(table,select='*',opts={}){let r=db.from(table).select(select);if(opts.order)r=r.order(opts.order,{ascending:opts.asc??false});if(opts.limit)r=r.limit(opts.limit);const out=await r;if(out.error)throw out.error;return out.data||[]}
async function loadAll(){
 const [patients,allergies,appointments,services,encounters,products,lots,prescriptions,rxItems,dispensing,invoices,invoiceItems,payments]=await Promise.all([
 q('patients','*',{order:'created_at'}),q('patient_allergies'),q('appointments'),q('services','*',{order:'name_th',asc:true}),q('encounters','*',{order:'started_at'}),q('products','*',{order:'name_th',asc:true}),q('inventory_lots','*',{order:'expiry_date',asc:true}),q('prescriptions','*',{order:'prescribed_at'}),q('prescription_items'),q('dispensing_orders','*',{order:'created_at'}),q('invoices','*',{order:'created_at'}),q('invoice_items'),q('payments')]);
 Object.assign(data,{patients,allergies,appointments,services,encounters,products,lots,prescriptions,rxItems,dispensing,invoices,invoiceItems,payments});render();
}
function options(arr,label){return '<option value="">เลือก</option>'+arr.map(x=>`<option value="${x.id}">${esc(label(x))}</option>`).join('')}
function render(){
 const po=options(data.patients,p=>`${p.hn} — ${patientName(p.id)}`),so=options(data.services,s=>`${s.service_code} — ${s.name_th}`),eo=options(data.encounters,encounterLabel),pro=options(data.products,p=>`${p.sku} — ${p.name_th}`);
 ['#appt-patient','#enc-patient'].forEach(s=>$(s).innerHTML=po);['#appt-service','#enc-service'].forEach(s=>$(s).innerHTML=so);['#rx-encounter','#bill-encounter'].forEach(s=>$(s).innerHTML=eo);['#rx-product','#lot-product'].forEach(s=>$(s).innerHTML=pro);
 const openInvoices=data.invoices.filter(i=>num(i.balance_due)>0&&i.status!=='void');$('#pay-invoice').innerHTML=options(openInvoices,i=>`${i.invoice_number} • ${patientName(i.patient_id)} • ฿${money(i.balance_due)}`);
 $('#stat-p').textContent=data.patients.length;$('#stat-a').textContent=data.appointments.filter(a=>a.appointment_date===today()).length;$('#stat-e').textContent=data.encounters.length;$('#stat-rx').textContent=data.dispensing.filter(d=>!['dispensed','cancelled','rejected'].includes(d.status)).length;$('#stat-ar').textContent='฿'+money(data.invoices.reduce((s,i)=>s+num(i.balance_due),0));
 $('#patient-list').innerHTML=data.patients.map(p=>{const a=data.allergies.filter(x=>x.patient_id===p.id&&x.status==='active');return `<div class="item"><div><b>${esc(p.hn)} ${esc(patientName(p.id))}</b><small>${esc(p.phone||'-')}${a.length?' • แพ้: '+esc(a.map(x=>x.allergen_name).join(', ')):''}</small></div><span class="badge">${esc(p.payment_right||'ทั่วไป')}</span></div>`}).join('')||'<p class="muted">ยังไม่มีผู้รับบริการ</p>';
 $('#appointment-list').innerHTML=data.appointments.sort((a,b)=>(a.appointment_date+a.appointment_time).localeCompare(b.appointment_date+b.appointment_time)).map(a=>`<div class="item"><div><b>${a.appointment_date} ${a.appointment_time||''}</b><small>${esc(patientName(a.patient_id))} • ${esc(data.services.find(s=>s.id===a.service_id)?.name_th||'-')}</small></div><span class="badge">${esc(a.status)}</span></div>`).join('')||'<p class="muted">ยังไม่มีนัด</p>';
 $('#encounter-list').innerHTML=data.encounters.slice(0,20).map(e=>`<div class="item"><div><b>${esc(e.encounter_no)} • ${esc(patientName(e.patient_id))}</b><small>${esc(e.thai_diagnosis||e.chief_complaint||'-')}</small></div><span class="badge">${esc(e.status)}</span></div>`).join('')||'<p class="muted">ยังไม่มี encounter</p>';
 $('#recent-list').innerHTML=data.encounters.slice(0,8).map(e=>`<div class="item"><div><b>${esc(patientName(e.patient_id))}</b><small>${new Date(e.started_at).toLocaleString('th-TH')} • ${esc(e.thai_diagnosis||e.chief_complaint||'')}</small></div></div>`).join('')||'<p class="muted">ยังไม่มีรายการ</p>';
 $('#inventory-list').innerHTML=data.lots.map(l=>{const p=data.products.find(x=>x.id===l.product_id);return `<div class="item"><div><b>${esc(p?.name_th||'-')} • Lot ${esc(l.lot_number)}</b><small>Exp ${esc(l.expiry_date||'-')} • ${esc(l.storage_location||'-')}</small></div><span class="badge">${num(l.current_quantity)} ${esc(l.unit)}</span></div>`}).join('')||'<p class="muted">ยังไม่มี Lot</p>';
 renderPharmacy();renderInvoices();bindDynamic();
}
function renderPharmacy(){
 $('#pharmacy-list').innerHTML=data.dispensing.map(d=>{const rx=data.prescriptions.find(x=>x.id===d.prescription_id),items=data.rxItems.filter(x=>x.prescription_id===rx?.id);return `<div class="item"><div><b>${esc(d.queue_number||'-')} • ${esc(patientName(rx?.patient_id))}</b><small>${items.map(i=>`${esc(data.products.find(p=>p.id===i.product_id)?.name_th||'-')} ${num(i.quantity_prescribed)} ${esc(i.unit)}`).join(' | ')}</small><small>สถานะ: ${esc(d.status)}</small></div>${d.status==='waiting'?`<button class="btn primary" data-dispense="${d.id}">จ่ายยา FEFO</button>`:''}</div>`}).join('')||'<p class="muted">ไม่มีคิวจ่ายยา</p>';
}
function renderInvoices(){
 $('#invoice-list').innerHTML=data.invoices.map(i=>`<div class="item"><div><b>${esc(i.invoice_number)} • ${esc(patientName(i.patient_id))}</b><small>รวม ฿${money(i.grand_total)} • ชำระ ฿${money(i.paid_amount)} • คงเหลือ ฿${money(i.balance_due)}</small></div><span class="badge">${esc(i.status)}</span></div>`).join('')||'<p class="muted">ยังไม่มี invoice</p>';
}
function bindDynamic(){$$('[data-dispense]').forEach(b=>b.onclick=()=>dispense(b.dataset.dispense))}
async function savePatient(e){e.preventDefault();if(!requireRole('patients'))return;const payload={hn:$('#p-hn').value.trim(),prefix:$('#p-prefix').value.trim(),first_name:$('#p-first').value.trim(),last_name:$('#p-last').value.trim(),national_id:$('#p-national').value.trim()||null,gender:$('#p-gender').value||null,date_of_birth:$('#p-dob').value||null,phone:$('#p-phone').value.trim()||null,address:$('#p-address').value.trim()||null,payment_right:$('#p-right').value.trim()||null,emergency_contact_name:$('#p-emergency').value.trim()||null,created_by:session.user.id};const id=$('#p-id').value;let r=id?await db.from('patients').update(payload).eq('id',id).select().single():await db.from('patients').insert(payload).select().single();if(r.error)throw r.error;const allergy=$('#p-allergy').value.trim();if(allergy&&!id){const ar=await db.from('patient_allergies').insert({patient_id:r.data.id,allergen_type:'other',allergen_name:allergy,status:'active',created_by:session.user.id});if(ar.error)throw ar.error}await audit(id?'update':'create','patients',r.data.id);e.target.reset();$('#p-id').value='';await loadAll();toast('บันทึกผู้รับบริการแล้ว')}
async function saveAppointment(e){e.preventDefault();if(!requireRole('appointments'))return;const r=await db.from('appointments').insert({patient_id:$('#appt-patient').value,appointment_date:$('#appt-date').value,appointment_time:$('#appt-time').value||null,service_id:$('#appt-service').value||null,room:$('#appt-room').value||null,notes:$('#appt-note').value||null,status:'scheduled',created_by:session.user.id}).select().single();if(r.error)throw r.error;await audit('create','appointments',r.data.id);e.target.reset();$('#appt-date').value=today();await loadAll();toast('บันทึกนัดแล้ว')}
function bp(){const [s,d]=($('#enc-bp').value||'').split('/').map(Number);return {systolic_bp:s||null,diastolic_bp:d||null}}
async function saveEncounter(e){e.preventDefault();if(!requireRole('clinical'))return;const no=`ENC-${Date.now()}`;const enc={encounter_no:no,patient_id:$('#enc-patient').value,status:'completed',chief_complaint:$('#enc-chief').value,present_illness:$('#enc-history').value||null,past_history:$('#enc-past').value||null,current_medications:$('#enc-past').value||null,red_flags:$('#enc-exam').value||null,general_examination:$('#enc-exam').value||null,modern_diagnosis:$('#enc-modern').value||null,thai_diagnosis:$('#enc-diagnosis').value,element_principle:$('#enc-element').value,seasonal_principle:$('#enc-season').value,practitioner_id:session.user.id,created_by:session.user.id,completed_at:new Date().toISOString()};const er=await db.from('encounters').insert(enc).select().single();if(er.error)throw er.error;const id=er.data.id,v={encounter_id:id,temperature:num($('#enc-temp').value)||null,pulse:num($('#enc-pulse').value)||null,respiration:num($('#enc-rr').value)||null,spo2:num($('#enc-spo2').value)||null,...bp(),recorded_by:session.user.id};let r=await db.from('vital_signs').insert(v);if(r.error)throw r.error;const before=num($('#enc-before').value),after=num($('#enc-after').value);r=await db.from('pain_assessments').insert([{encounter_id:id,assessment_stage:'before',score:before,assessed_by:session.user.id},{encounter_id:id,assessment_stage:'after',score:after,assessed_by:session.user.id}]);if(r.error)throw r.error;const service=$('#enc-service').value||null;const order=await db.from('treatment_orders').insert({encounter_id:id,service_id:service,order_type:'treatment',instructions:$('#enc-treatment').value||null,treatment_area:$('#enc-area').value||null,status:'completed',ordered_by:session.user.id}).select().single();if(order.error)throw order.error;r=await db.from('treatment_sessions').insert({treatment_order_id:order.data.id,encounter_id:id,service_id:service,practitioner_id:session.user.id,started_at:new Date().toISOString(),ended_at:new Date().toISOString(),treatment_area:$('#enc-area').value||null,procedure_notes:$('#enc-treatment').value||null,outcome:$('#enc-outcome').value||null,status:'completed'});if(r.error)throw r.error;if($('#enc-next').value||$('#enc-advice').value){r=await db.from('followups').insert({encounter_id:id,next_visit_date:$('#enc-next').value||null,advice:$('#enc-advice').value||null,outcome:$('#enc-outcome').value||null,created_by:session.user.id});if(r.error)throw r.error}await audit('create','encounters',id);e.target.reset();await loadAll();toast('บันทึก Encounter และ Treatment แล้ว')}
async function savePrescription(e){e.preventDefault();if(!requireRole('prescription'))return;const enc=data.encounters.find(x=>x.id===$('#rx-encounter').value);if(!enc)throw new Error('ไม่พบ Encounter');const no=`RX-${Date.now()}`;const rx=await db.from('prescriptions').insert({prescription_no:no,encounter_id:enc.id,patient_id:enc.patient_id,prescriber_id:session.user.id,status:'sent_to_pharmacy',clinical_notes:$('#rx-instructions').value||null,sent_to_pharmacy_at:new Date().toISOString()}).select().single();if(rx.error)throw rx.error;let r=await db.from('prescription_items').insert({prescription_id:rx.data.id,product_id:$('#rx-product').value,dose:$('#rx-dose').value||null,frequency:$('#rx-frequency').value||null,quantity_prescribed:num($('#rx-qty').value),unit:$('#rx-unit').value,instructions:$('#rx-instructions').value||null,status:'ordered'});if(r.error)throw r.error;r=await db.from('dispensing_orders').insert({prescription_id:rx.data.id,queue_number:`Q-${String(Date.now()).slice(-5)}`,status:'waiting'});if(r.error)throw r.error;await audit('create','prescriptions',rx.data.id);e.target.reset();await loadAll();toast('ส่งไปห้องจ่ายยาแล้ว')}
async function saveLot(e){e.preventDefault();if(!requireRole('inventory'))return;const qty=num($('#lot-qty').value);const lr=await db.from('inventory_lots').insert({product_id:$('#lot-product').value,lot_number:$('#lot-number').value,expiry_date:$('#lot-exp').value||null,received_quantity:qty,current_quantity:0,unit:$('#lot-unit').value,purchase_cost:num($('#lot-cost').value),storage_location:$('#lot-location').value||null,created_by:session.user.id}).select().single();if(lr.error)throw lr.error;const r=await db.from('stock_movements').insert({inventory_lot_id:lr.data.id,movement_type:'receive',quantity:qty,direction:'in',reference_type:'goods_receipt',reference_id:lr.data.id,performed_by:session.user.id});if(r.error)throw r.error;await audit('receive','inventory_lots',lr.data.id,{qty});e.target.reset();await loadAll();toast('รับสินค้าและเพิ่ม Stock แล้ว')}
async function dispense(orderId){if(!requireRole('pharmacy'))return;const d=data.dispensing.find(x=>x.id===orderId),rx=data.prescriptions.find(x=>x.id===d.prescription_id),items=data.rxItems.filter(x=>x.prescription_id===rx.id);if(!confirm(`ยืนยันจ่ายยา ${patientName(rx.patient_id)}?`))return;for(const item of items){let remain=num(item.quantity_prescribed);const lots=data.lots.filter(l=>l.product_id===item.product_id&&l.status==='active'&&num(l.current_quantity)>0&&(!l.expiry_date||l.expiry_date>=today())).sort((a,b)=>(a.expiry_date||'9999').localeCompare(b.expiry_date||'9999'));for(const lot of lots){if(remain<=0)break;const qty=Math.min(remain,num(lot.current_quantity));let r=await db.from('dispensing_items').insert({dispensing_order_id:d.id,prescription_item_id:item.id,inventory_lot_id:lot.id,quantity_dispensed:qty,unit:item.unit,unit_price:0,status:'dispensed'});if(r.error)throw r.error;r=await db.from('stock_movements').insert({inventory_lot_id:lot.id,movement_type:'dispense',quantity:qty,direction:'out',reference_type:'dispensing_order',reference_id:d.id,performed_by:session.user.id});if(r.error)throw r.error;remain-=qty}if(remain>0)throw new Error(`สต็อกไม่พอสำหรับ ${data.products.find(p=>p.id===item.product_id)?.name_th||'ยา'}`)}let r=await db.from('dispensing_orders').update({status:'dispensed',reviewed_by:session.user.id,reviewed_at:new Date().toISOString(),prepared_by:session.user.id,prepared_at:new Date().toISOString(),dispensed_by:session.user.id,dispensed_at:new Date().toISOString()}).eq('id',d.id);if(r.error)throw r.error;r=await db.from('prescriptions').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',rx.id);if(r.error)throw r.error;await audit('dispense','dispensing_orders',d.id);await loadAll();toast('จ่ายยาและตัด Stock แบบ FEFO แล้ว')}
async function saveInvoice(e){e.preventDefault();if(!requireRole('billing'))return;const enc=data.encounters.find(x=>x.id===$('#bill-encounter').value);if(!enc)throw new Error('ไม่พบ Encounter');const service=num($('#bill-service').value),medicine=num($('#bill-medicine').value),discount=num($('#bill-discount').value),subtotal=service+medicine,total=Math.max(0,subtotal-discount),no=`INV-${Date.now()}`;const ir=await db.from('invoices').insert({invoice_number:no,patient_id:enc.patient_id,encounter_id:enc.id,status:'awaiting_payment',subtotal,discount_total:discount,tax_total:0,grand_total:total,paid_amount:0,balance_due:total,issued_at:new Date().toISOString(),created_by:session.user.id}).select().single();if(ir.error)throw ir.error;const lines=[];if(service>0)lines.push({invoice_id:ir.data.id,item_type:'service',description:'ค่าบริการรักษา',quantity:1,unit_price:service,line_total:service});if(medicine>0)lines.push({invoice_id:ir.data.id,item_type:'product',description:'ค่ายาและสมุนไพร',quantity:1,unit_price:medicine,line_total:medicine});if(lines.length){const r=await db.from('invoice_items').insert(lines);if(r.error)throw r.error}await audit('create','invoices',ir.data.id);e.target.reset();await loadAll();toast('ออก Invoice แล้ว')}
async function savePayment(e){e.preventDefault();if(!requireRole('billing'))return;const invoice=data.invoices.find(x=>x.id===$('#pay-invoice').value),amount=num($('#pay-amount').value);if(!invoice)throw new Error('ไม่พบ Invoice');if(amount>num(invoice.balance_due))throw new Error('จำนวนชำระเกินยอดคงเหลือ');let r=await db.from('payments').insert({invoice_id:invoice.id,payment_reference:`PAY-${Date.now()}`,provider:'manual',channel:$('#pay-channel').value,amount,currency:'THB',status:'paid',paid_at:new Date().toISOString(),received_by:session.user.id});if(r.error)throw r.error;const paid=num(invoice.paid_amount)+amount,balance=Math.max(0,num(invoice.grand_total)-paid);r=await db.from('invoices').update({paid_amount:paid,balance_due:balance,status:balance===0?'paid':'partially_paid'}).eq('id',invoice.id);if(r.error)throw r.error;await audit('payment','invoices',invoice.id,{amount,channel:$('#pay-channel').value});e.target.reset();await loadAll();toast('รับชำระแล้ว')}
async function loadAudit(){if(role!=='admin'){$('#audit-list').innerHTML='<p class="muted">เฉพาะ admin</p>';return}const r=await db.from('audit_logs').select('*').order('occurred_at',{ascending:false}).limit(100);$('#audit-list').innerHTML=r.error?`<p>${esc(r.error.message)}</p>`:(r.data||[]).map(x=>`<div class="item"><div><b>${esc(x.action)} • ${esc(x.entity)}</b><small>${new Date(x.occurred_at).toLocaleString('th-TH')}</small></div></div>`).join('')}
function resetLock(){clearTimeout(lockTimer);lockTimer=setTimeout(async()=>{$('#lock').classList.add('show');await audit('auto_lock','session',session.user.id)},LOCK_MS)}
function setup(){
 $$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));if(b.dataset.view==='audit')loadAudit()});
 $('#patient-form').onsubmit=wrap(savePatient);$('#appointment-form').onsubmit=wrap(saveAppointment);$('#encounter-form').onsubmit=wrap(saveEncounter);$('#prescription-form').onsubmit=wrap(savePrescription);$('#lot-form').onsubmit=wrap(saveLot);$('#invoice-form').onsubmit=wrap(saveInvoice);$('#payment-form').onsubmit=wrap(savePayment);
 $('#logout').onclick=async()=>{await audit('logout','session',session.user.id);await db.auth.signOut({scope:'local'});location.replace('/login-v3.html')};$('#unlock').onclick=()=>{$('#lock').classList.remove('show');resetLock()};['pointerdown','keydown','touchstart','scroll'].forEach(ev=>document.addEventListener(ev,()=>{if(session&&!$('#lock').classList.contains('show'))resetLock()},{passive:true}));$('#appt-date').value=today();
}
const wrap=fn=>async e=>{try{await fn(e)}catch(err){console.error(err);alert(err.message||String(err))}};
async function init(){try{if(!cfg.supabaseUrl||!cfg.publishableKey)throw new Error('Missing Supabase configuration');db=supabase.createClient(cfg.supabaseUrl,cfg.publishableKey,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const s=await db.auth.getSession();if(s.error)throw s.error;session=s.data.session;if(!session){location.replace('/login-v3.html');return}const p=await db.from('profiles').select('role,email').eq('id',session.user.id).single();if(p.error)throw p.error;role=p.data.role||'viewer';$('#role').textContent=role;$('#identity').textContent=session.user.email||p.data.email||'';setup();await loadAll();await audit('login','session',session.user.id);$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');resetLock()}catch(e){console.error(e);$('#boot-title').textContent='เปิดระบบไม่สำเร็จ';$('#boot-error').textContent=e.message||String(e)}}
document.addEventListener('DOMContentLoaded',init);
})();