(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let db,session,profile,role='viewer';
let data={products:[],sales:[],items:[],patients:[],prescriptions:[],dispensing:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(v||0),money=v=>num(v).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function fail(e){console.error(e);alert(e?.message||String(e))}
async function waitRuntime(){for(let i=0;i<50;i++){if(window.ChananyaRuntime)return window.ChananyaRuntime;await new Promise(r=>setTimeout(r,100))}throw new Error('ChananyaRuntime ไม่พร้อมใช้งาน')}
async function q(t,s='*',o){let r=db.from(t).select(s);if(o)r=r.order(o,{ascending:false});const x=await r;if(x.error)throw x.error;return x.data||[]}
async function load(){const [products,sales,items,patients,prescriptions,dispensing]=await Promise.all([q('products'),q('pharmacy_counter_sales','*','created_at'),q('pharmacy_counter_sale_items'),q('patients'),q('prescriptions','*','prescribed_at'),q('dispensing_orders','*','created_at')]);Object.assign(data,{products,sales,items,patients,prescriptions,dispensing});render()}
function product(id){return data.products.find(x=>x.id===id)}
function patient(id){return data.patients.find(x=>x.id===id)}
function opts(arr,label){return '<option value="">เลือก</option>'+arr.map(x=>`<option value="${x.id}">${esc(label(x))}</option>`).join('')}
function render(){const drafts=data.sales.filter(s=>['draft','reviewed','dispensed'].includes(s.status));$('#item-sale').innerHTML=opts(drafts,s=>`${s.sale_no} — ${s.customer_name||'Walk-in'}`);$('#item-product').innerHTML=opts(data.products,p=>`${p.sku} — ${p.name_th}`);renderRx();renderWalkin();renderHistory();window.dispatchEvent(new CustomEvent('chananya:pharmacy-rendered'))}
function renderRx(){const rows=data.dispensing.map(o=>{const rx=data.prescriptions.find(r=>r.id===o.prescription_id),p=patient(rx?.patient_id);return `<div class="item" data-dispensing-order-id="${esc(o.id)}"><div><b>${esc(o.queue_number||'-')} • ${esc(p?`${p.hn} ${p.first_name} ${p.last_name}`:'-')}</b><small>${esc(rx?.prescription_no||'-')} • ${esc(o.status)}</small></div><span class="badge">${esc(o.status)}</span></div>`}).join('');$('#rx-list').innerHTML=rows||'<p class="muted">ไม่มีคิวใบสั่งยาจากหมอ</p>'}
function itemRows(saleId){return data.items.filter(i=>i.sale_id===saleId).map(i=>`<div class="drug"><b>${esc(product(i.product_id)?.name_th||'-')}</b> ${num(i.quantity_requested)} ${esc(i.unit)} × ฿${money(i.unit_price)}<br><small>${esc(i.dose||'')} ${esc(i.frequency||'')} ${esc(i.duration||'')}</small></div>`).join('')}
function renderWalkin(){const rows=data.sales.filter(s=>!['paid','cancelled'].includes(s.status)).map(s=>{const buttons=[];if(s.status==='draft')buttons.push(`<button class="btn primary" data-act="review" data-id="${s.id}">เภสัชกร Review</button>`);if(s.status==='reviewed')buttons.push(`<button class="btn primary" data-act="dispense" data-id="${s.id}">จ่ายยา FEFO</button>`);if(s.status==='dispensed')buttons.push(`<button class="btn primary" data-act="billing" data-id="${s.id}">Submit Billing</button>`);return `<div class="item column" data-sale-id="${esc(s.id)}"><div class="row"><b>${esc(s.sale_no)} • ${esc(s.customer_name||'Walk-in')}</b><span class="badge">${esc(s.status)}</span></div><small>อาการ: ${esc(s.presenting_symptoms||'-')} • แพ้ยา: ${esc(s.allergy_notes||'-')}</small>${itemRows(s.id)}<div class="right">${buttons.join('')}</div></div>`}).join('');$('#walkin-list').innerHTML=rows||'<p class="muted">ยังไม่มีรายการ Walk-in</p>';bindActions()}
function renderHistory(){const rows=data.sales.map(s=>`<div class="item" data-sale-id="${esc(s.id)}"><div><b>${esc(s.sale_no)} • ${esc(s.customer_name||'Walk-in')}</b><small>ยอด ฿${money(s.grand_total)} • ${new Date(s.created_at).toLocaleString('th-TH')}</small></div><span class="badge">${esc(s.status)}</span></div>`).join('');$('#history-list').innerHTML=rows||'<p class="muted">ยังไม่มีประวัติ</p>'}
function bindActions(){$$('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act,b.dataset.id).catch(fail))}
async function act(a,id){if(a==='review'){const r=await db.from('pharmacy_counter_sales').update({status:'reviewed',reviewed_by:session.user.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;toast('Review แล้ว')}if(a==='dispense'){const r=await db.rpc('dispense_pharmacy_counter_sale',{p_sale_id:id});if(r.error)throw r.error;toast('จ่ายยาและตัด Stock แล้ว')}if(a==='billing'){const r=await db.from('pharmacy_counter_sales').update({status:'submitted_to_billing',submitted_to_billing_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;toast('ส่ง Billing แล้ว')}await load()}
async function saveSale(e){e.preventDefault();const payload={sale_no:`PS-${Date.now()}`,customer_name:$('#customer-name').value.trim()||null,customer_phone:$('#customer-phone').value.trim()||null,presenting_symptoms:$('#symptoms').value.trim(),allergy_notes:$('#allergies').value.trim()||null,current_medicines:$('#current-meds').value.trim()||null,contraindication_notes:$('#contra').value.trim()||null,pharmacist_assessment:$('#assessment').value.trim(),advice:$('#advice').value.trim()||null,created_by:session.user.id};const r=await db.from('pharmacy_counter_sales').insert(payload);if(r.error)throw r.error;e.target.reset();await load();toast('สร้างรายการ Walk-in แล้ว')}
async function saveItem(e){e.preventDefault();const payload={sale_id:$('#item-sale').value,product_id:$('#item-product').value,quantity_requested:num($('#item-qty').value),unit:$('#item-unit').value.trim(),unit_price:num($('#item-price').value),dose:$('#item-dose').value.trim()||null,frequency:$('#item-frequency').value.trim()||null,duration:$('#item-duration').value.trim()||null,instructions:$('#item-instructions').value.trim()||null};const r=await db.from('pharmacy_counter_sale_items').insert(payload);if(r.error)throw r.error;e.target.reset();await load();toast('เพิ่มยาแล้ว')}
async function init(){try{const R=await waitRuntime();db=R.getDb();session=await R.getSession();if(!session){location.replace('login.html');return}profile=await R.getProfile(session.user.id);if(!profile)throw new Error('ไม่พบ Profile');role=R.roleOf(profile)||'viewer';if(!R.can(profile,'pharmacy_operate'))throw new Error('บัญชีนี้ไม่มีสิทธิ์ Pharmacy');$('#identity').textContent=`${profile.full_name||session.user.email} • ${session.user.email}`;$('#role').textContent=role;$('#role').dataset.effectiveRole=role;$('#app').classList.remove('hidden');$('#boot').classList.add('hidden');await load()}catch(e){console.error(e);$('#boot-error').textContent=e.message}}
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))});$('#sale-form').addEventListener('submit',e=>saveSale(e).catch(fail));$('#item-form').addEventListener('submit',e=>saveItem(e).catch(fail));$('#logout').onclick=async()=>{if(db)await db.auth.signOut();location.replace('login.html')};init();
})();