(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let db,session,profile,role='viewer';
let data={products:[],sales:[],items:[],patients:[],prescriptions:[],dispensing:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(v||0),money=v=>num(v).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function fail(e){console.error(e);alert(e?.message||String(e))}
async function waitRuntime(){for(let i=0;i<50;i++){if(window.ChananyaRuntime)return window.ChananyaRuntime;await new Promise(r=>setTimeout(r,100))}throw new Error('ChananyaRuntime ไม่พร้อมใช้งาน')}
async function q(t,s='*',o){let r=db.from(t).select(s);if(o)r=r.order(o,{ascending:false});const x=await r;if(x.error)throw x.error;return x.data||[]}
async function load(){const [products,sales,items,patients,prescriptions,dispensing]=await Promise.all([q('products','*','updated_at'),q('pharmacy_counter_sales','*','created_at'),q('pharmacy_counter_sale_items'),q('patients'),q('prescriptions','*','prescribed_at'),q('dispensing_orders','*','created_at')]);Object.assign(data,{products,sales,items,patients,prescriptions,dispensing});render()}
function product(id){return data.products.find(x=>x.id===id)}
function patient(id){return data.patients.find(x=>x.id===id)}
function opts(arr,label,selected=''){return '<option value="">เลือก</option>'+arr.map(x=>`<option value="${esc(x.id)}"${x.id===selected?' selected':''}>${esc(label(x))}</option>`).join('')}
function activeProducts(){return data.products.filter(p=>p.active!==false)}
function filteredProducts(){const term=($('#item-product-search')?.value||'').trim().toLowerCase();return activeProducts().filter(p=>!term||[p.sku,p.name_th,p.name_en,p.category,p.dosage_form].some(v=>String(v||'').toLowerCase().includes(term)))}
function refillProductSelect(){const el=$('#item-product');if(!el)return;const selected=el.value;el.innerHTML=opts(filteredProducts(),p=>`${p.sku} — ${p.name_th}`,selected);if(selected&&filteredProducts().some(p=>p.id===selected))el.value=selected}
function render(){const saleSel=$('#item-sale')?.value||'',prodSel=$('#item-product')?.value||'';const drafts=data.sales.filter(s=>['draft','reviewed','dispensed'].includes(s.status));$('#item-sale').innerHTML=opts(drafts,s=>`${s.sale_no} — ${s.customer_name||'Walk-in'}`,saleSel);$('#item-product').innerHTML=opts(filteredProducts(),p=>`${p.sku} — ${p.name_th}`,prodSel);renderRx();renderWalkin();renderProducts();renderHistory();window.dispatchEvent(new CustomEvent('chananya:pharmacy-rendered'))}
function renderRx(){const rows=data.dispensing.map(o=>{const rx=data.prescriptions.find(r=>r.id===o.prescription_id),p=patient(rx?.patient_id);return `<div class="item" data-dispensing-order-id="${esc(o.id)}"><div><b>${esc(o.queue_number||'-')} • ${esc(p?`${p.hn} ${p.first_name} ${p.last_name}`:'-')}</b><small>${esc(rx?.prescription_no||'-')} • ${esc(o.status)}</small></div><span class="badge">${esc(o.status)}</span></div>`}).join('');$('#rx-list').innerHTML=rows||'<p class="muted">ไม่มีคิวใบสั่งยาจากหมอ</p>'}
function itemRows(saleId){return data.items.filter(i=>i.sale_id===saleId).map(i=>`<div class="drug"><b>${esc(product(i.product_id)?.name_th||'-')}</b> ${num(i.quantity_requested)} ${esc(i.unit)} × ฿${money(i.unit_price)}<br><small>${esc(i.dose||'')} ${esc(i.frequency||'')} ${esc(i.duration||'')}</small><div class="right"><button class="btn ghost" data-act="remove-item" data-id="${esc(i.id)}">ลบรายการ</button></div></div>`).join('')}
function renderWalkin(){const rows=data.sales.filter(s=>!['paid','cancelled'].includes(s.status)).map(s=>{const buttons=[];if(s.status==='draft')buttons.push(`<button class="btn primary" data-act="review" data-id="${s.id}">เภสัชกร Review</button>`);if(s.status==='reviewed')buttons.push(`<button class="btn primary" data-act="dispense" data-id="${s.id}">จ่ายยา FEFO</button>`);if(s.status==='dispensed')buttons.push(`<button class="btn primary" data-act="billing" data-id="${s.id}">Submit Billing</button>`);return `<div class="item column" data-sale-id="${esc(s.id)}"><div class="row"><b>${esc(s.sale_no)} • ${esc(s.customer_name||'Walk-in')}</b><span class="badge">${esc(s.status)}</span></div><small>อาการ: ${esc(s.presenting_symptoms||'-')} • แพ้ยา: ${esc(s.allergy_notes||'-')}</small>${itemRows(s.id)}<div class="right">${buttons.join('')}</div></div>`}).join('');$('#walkin-list').innerHTML=rows||'<p class="muted">ยังไม่มีรายการ Walk-in</p>';bindActions()}
function renderProducts(){const box=$('#product-list');if(!box)return;const term=($('#product-master-search')?.value||'').trim().toLowerCase(),showInactive=$('#show-inactive-products')?.checked;const rows=data.products.filter(p=>(showInactive||p.active!==false)&&(!term||[p.sku,p.name_th,p.name_en,p.category,p.dosage_form].some(v=>String(v||'').toLowerCase().includes(term)))).map(p=>`<div class="item column"><div class="row"><div><b>${esc(p.sku)} • ${esc(p.name_th)}</b><small>${esc(p.category)} • Stock ${esc(p.stock_unit)} • Dispense ${esc(p.dispense_unit)}</small></div><span class="badge">${p.active===false?'inactive':'active'}</span></div><div class="right"><button class="btn ghost" data-act="edit-product" data-id="${esc(p.id)}">แก้ไข</button><button class="btn ${p.active===false?'primary':'danger'}" data-act="toggle-product" data-id="${esc(p.id)}">${p.active===false?'เปิดใช้งาน':'ปิดใช้งาน'}</button></div></div>`).join('');box.innerHTML=rows||'<p class="muted">ไม่พบผลิตภัณฑ์</p>';bindActions()}
function renderHistory(){const rows=data.sales.map(s=>`<div class="item" data-sale-id="${esc(s.id)}"><div><b>${esc(s.sale_no)} • ${esc(s.customer_name||'Walk-in')}</b><small>ยอด ฿${money(s.grand_total)} • ${new Date(s.created_at).toLocaleString('th-TH')}</small></div><span class="badge">${esc(s.status)}</span></div>`).join('');$('#history-list').innerHTML=rows||'<p class="muted">ยังไม่มีประวัติ</p>'}
function bindActions(){$$('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act,b.dataset.id).catch(fail))}
async function act(a,id){if(a==='review'){const r=await db.from('pharmacy_counter_sales').update({status:'reviewed',reviewed_by:session.user.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;toast('Review แล้ว')}else if(a==='dispense'){const r=await db.rpc('dispense_pharmacy_counter_sale',{p_sale_id:id});if(r.error)throw r.error;toast('จ่ายยาและตัด Stock แล้ว')}else if(a==='billing'){const r=await db.from('pharmacy_counter_sales').update({status:'submitted_to_billing',submitted_to_billing_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;toast('ส่ง Billing แล้ว')}else if(a==='remove-item'){const it=data.items.find(x=>x.id===id),sale=data.sales.find(x=>x.id===it?.sale_id);if(!it)return;if(sale?.status!=='draft')throw new Error('ลบรายการยาได้เฉพาะรายการขายสถานะ draft');if(!confirm('ลบรายการยานี้หรือไม่?'))return;const r=await db.from('pharmacy_counter_sale_items').delete().eq('id',id);if(r.error)throw r.error;toast('ลบรายการยาแล้ว')}else if(a==='edit-product'){fillProductForm(id);return}else if(a==='toggle-product'){const p=product(id);if(!p)return;const next=p.active===false;const r=await db.from('products').update({active:next,updated_by:session.user.id,deactivated_at:next?null:new Date().toISOString(),deactivated_by:next?null:session.user.id}).eq('id',id);if(r.error)throw r.error;toast(next?'เปิดใช้งานผลิตภัณฑ์แล้ว':'ปิดใช้งานผลิตภัณฑ์แล้ว')}await load()}
async function saveSale(e){e.preventDefault();const payload={sale_no:`PS-${Date.now()}`,customer_name:$('#customer-name').value.trim()||null,customer_phone:$('#customer-phone').value.trim()||null,presenting_symptoms:$('#symptoms').value.trim(),allergy_notes:$('#allergies').value.trim()||null,current_medicines:$('#current-meds').value.trim()||null,contraindication_notes:$('#contra').value.trim()||null,pharmacist_assessment:$('#assessment').value.trim(),advice:$('#advice').value.trim()||null,created_by:session.user.id};const r=await db.from('pharmacy_counter_sales').insert(payload);if(r.error)throw r.error;e.target.reset();await load();toast('สร้างรายการ Walk-in แล้ว')}
async function saveItem(e){e.preventDefault();const productId=$('#item-product').value;if(!productId)throw new Error('กรุณาเลือกยา/ผลิตภัณฑ์');const payload={sale_id:$('#item-sale').value,product_id:productId,quantity_requested:num($('#item-qty').value),unit:$('#item-unit').value.trim(),unit_price:num($('#item-price').value),dose:$('#item-dose').value.trim()||null,frequency:$('#item-frequency').value.trim()||null,duration:$('#item-duration').value.trim()||null,instructions:$('#item-instructions').value.trim()||null};const r=await db.from('pharmacy_counter_sale_items').insert(payload);if(r.error)throw r.error;e.target.reset();$('#item-product-search').value='';await load();toast('เพิ่มยาแล้ว')}
function resetProductForm(){const f=$('#product-form');if(f)f.reset();$('#product-id').value='';$('#product-conversion').value='1';$('#product-cost').value='0';$('#product-min-stock').value='0';$('#product-reorder').value='0'}
function fillProductForm(id){const p=product(id);if(!p)return;$('#product-id').value=p.id;$('#product-sku').value=p.sku||'';$('#product-name-th').value=p.name_th||'';$('#product-name-en').value=p.name_en||'';$('#product-category').value=p.category||'';$('#product-dosage-form').value=p.dosage_form||'';$('#product-purchase-unit').value=p.purchase_unit||'';$('#product-stock-unit').value=p.stock_unit||'';$('#product-dispense-unit').value=p.dispense_unit||'';$('#product-conversion').value=p.conversion_factor??1;$('#product-cost').value=p.standard_cost??0;$('#product-min-stock').value=p.min_stock??0;$('#product-reorder').value=p.reorder_level??0;$('#product-sku').focus()}
async function saveProduct(e){e.preventDefault();const id=$('#product-id').value||null;const payload={sku:$('#product-sku').value.trim(),name_th:$('#product-name-th').value.trim(),name_en:$('#product-name-en').value.trim()||null,category:$('#product-category').value.trim(),dosage_form:$('#product-dosage-form').value.trim()||null,purchase_unit:$('#product-purchase-unit').value.trim()||null,stock_unit:$('#product-stock-unit').value.trim(),dispense_unit:$('#product-dispense-unit').value.trim(),conversion_factor:num($('#product-conversion').value)||1,standard_cost:num($('#product-cost').value),min_stock:num($('#product-min-stock').value),reorder_level:num($('#product-reorder').value),active:true,updated_by:session.user.id};let r;if(id)r=await db.from('products').update(payload).eq('id',id);else r=await db.from('products').insert({...payload,created_by:session.user.id});if(r.error)throw r.error;resetProductForm();await load();toast(id?'แก้ไขผลิตภัณฑ์แล้ว':'เพิ่มผลิตภัณฑ์แล้ว')}
async function init(){try{const R=await waitRuntime();db=R.getDb();session=await R.getSession();if(!session){location.replace('login.html');return}profile=await R.getProfile(session.user.id);if(!profile)throw new Error('ไม่พบ Profile');const roles=R.rolesOf(profile);role=roles.effectiveRole||'viewer';if(!R.can(profile,'pharmacy_operate'))throw new Error('บัญชีนี้ไม่มีสิทธิ์ Pharmacy');$('#identity').textContent=`${profile.full_name||session.user.email} • ${session.user.email}`;const badge=$('#role');badge.textContent=role;badge.dataset.systemRole=roles.systemRole;badge.dataset.operationalRole=roles.operationalRole;badge.dataset.effectiveRole=role;$('#app').classList.remove('hidden');$('#boot').classList.add('hidden');await load()}catch(e){console.error(e);$('#boot-error').textContent=e.message}}
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view))});$('#sale-form').addEventListener('submit',e=>saveSale(e).catch(fail));$('#item-form').addEventListener('submit',e=>saveItem(e).catch(fail));$('#product-form')?.addEventListener('submit',e=>saveProduct(e).catch(fail));$('#product-cancel')?.addEventListener('click',resetProductForm);$('#item-product-search')?.addEventListener('input',refillProductSelect);$('#product-master-search')?.addEventListener('input',renderProducts);$('#show-inactive-products')?.addEventListener('change',renderProducts);$('#logout').onclick=async()=>{if(db)await db.auth.signOut();location.replace('login.html')};init();
})();
