import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';
const sandbox={window:{},TextEncoder,crypto:{randomUUID:()=> 'request-fixed',subtle:webcrypto.subtle}};
vm.runInNewContext(fs.readFileSync(new URL('../clarification-action.js',import.meta.url),'utf8'),sandbox);
const {create}=sandbox.window.CnyosClarificationAction;
const calls=[];
let saved=null, loseResponse=true, wrongRead=false;
const db={rpc:async(name,args)=>{
  assert.equal(name,'manage_prescription_clarification'); calls.push({...args});
  if(args.p_action==='read') return {data:wrongRead ? {...saved,order_id:'other-order'}:saved};
  saved={order_id:'order',request_id:args.p_request_id,requested_by:'pharmacy',question:args.p_text,status:'open'};
  if(loseResponse) throw new Error('NETWORK_LOST_AFTER_SAVE');
  return {data:saved};
}};
const decision=create({db,orderId:'order',actorId:'pharmacy',action:'open',text:'  Synthetic question  '});
await assert.rejects(decision.submit(),/NETWORK_LOST/);
assert.equal(calls.length,1);
assert.equal((await decision.recover()).question,'Synthetic question');
assert.equal(calls.length,2); assert.equal(calls[1].p_action,'read');
await decision.submit(); assert.equal(calls.length,2,'confirmed decisions must not submit twice');
loseResponse=false; wrongRead=true;
const mismatch=create({db,orderId:'order',actorId:'pharmacy',action:'open',text:'Other question'});
await assert.rejects(mismatch.submit(),/READBACK_MISMATCH/);
wrongRead=false; await mismatch.recover();
for(const action of ['answer','acknowledge']) {
  let count=0;
  const payload={order_id:'order',request_id:'original',status:action==='answer'?'answered':'resolved',
    answered_by:'doctor',answer:'Synthetic answer',acknowledged_by:'pharmacy'};
  const actorId=action==='answer'?'doctor':'pharmacy';
  const client={rpc:async(_name,args)=>{count++;return {data:args.p_action==='read'?payload:{}};}};
  const item=create({db:client,orderId:'order',actorId,action,requestId:'original',text:'Synthetic answer'});
  assert.equal((await item.submit()).status,payload.status); assert.equal(count,2);
  const wrongActor=create({db:client,orderId:'order',actorId:'someone-else',action,requestId:'original',text:'Synthetic answer'});
  await assert.rejects(wrongActor.submit(),/READBACK_MISMATCH/);
}
let release;
const pending=create({db:{rpc:()=>new Promise(resolve=>{release=resolve;})},orderId:'order',actorId:'pharmacy',action:'open',text:'Synthetic pending'});
const first=pending.submit();
await assert.rejects(pending.submit(),/ACTION_PENDING/);
release({error:new Error('DENIED')}); await assert.rejects(first,/DENIED/);
assert.throws(()=>create({db,orderId:'order',actorId:'doctor',action:'answer',text:'Valid text'}),/REQUEST_REQUIRED/);
assert.throws(()=>create({db,orderId:'order',actorId:'pharmacy',action:'open',text:'x'}),/INPUT_INVALID/);
const rejection={code:'P0001',message:'CLARIFICATION_ALREADY_OPEN'};
const rejected=create({db:{rpc:async()=>({error:rejection})},orderId:'order',actorId:'pharmacy',action:'open',text:'Synthetic rejected'});
await assert.rejects(rejected.submit()); assert.equal(rejected.canDiscard(),true);
let attempt=0;
const uncertain=create({db:{rpc:async()=>{if(++attempt===1) throw new Error('lost');return {error:rejection};}},
  orderId:'order',actorId:'pharmacy',action:'open',text:'Synthetic uncertain'});
await assert.rejects(uncertain.submit()); assert.equal(uncertain.canDiscard(),false);
await assert.rejects(uncertain.submit()); assert.equal(uncertain.canDiscard(),false,'rejected retry cannot erase earlier uncertainty');
const readDenied=create({db:{rpc:async(_name,args)=>args.p_action==='read'?{error:{code:'42501',message:'denied'}}:{data:{}}},
  orderId:'order',actorId:'pharmacy',action:'open',text:'Synthetic committed'});
await assert.rejects(readDenied.submit()); assert.equal(readDenied.canDiscard(),false,'failed readback does not prove failed write');
console.log('Clarification action controller passed: exact readback, read-only recovery, stable request, duplicate suppression, definitive rejection and preserved prior uncertainty.');

const {prepare,restore}=sandbox.window.CnyosClarificationAction;
const records=new Map();
const storage={getItem:key=>records.get(key)??null,setItem:(key,value)=>records.set(key,value),removeItem:key=>records.delete(key)};
const options={db,orderId:'order',actorId:'pharmacy',action:'open',text:'Synthetic journal question'};
loseResponse=true; wrongRead=false;
const tracked=await prepare(options,storage);
assert.equal(records.size,1);
assert.ok(![...records.values()][0].includes(options.text),'journal must not contain clinical text');
await assert.rejects(tracked.submit(),/NETWORK_LOST/);
const countBefore=calls.length;
const restored=restore(options,storage);
assert.equal(restored.needsText(),true);
assert.equal((await restored.recover()).question,options.text);
assert.equal(calls.length,countBefore+1);
assert.equal(calls.at(-1).p_action,'read');
assert.equal(records.size,0);
await restored.submit('changed');
assert.equal(calls.length,countBefore+1,'confirmed recovered decision cannot write again');

let retryCalls=[];
const retryDb={rpc:async(_name,args)=>{retryCalls.push(args);return {error:rejection};}};
await prepare({...options,db:retryDb},storage);
const retry=restore({...options,db:retryDb},storage);
await assert.rejects(retry.submit('different'),/ORIGINAL_TEXT_REQUIRED/);
assert.equal(retryCalls.length,0);
await assert.rejects(retry.submit(options.text));
assert.equal(retryCalls[0].p_request_id,'request-fixed');
assert.equal(retry.canDiscard(),false,'reload retry must preserve uncertainty');
assert.throws(()=>retry.discard(),/OUTCOME_UNCERTAIN/);
assert.equal(records.size,1);
assert.equal(restore({...options,actorId:'other'},storage),null);
assert.equal(restore({...options,orderId:'other'},storage),null);
await assert.rejects(prepare(options,storage),/RECOVERY_REQUIRED/);
records.clear();
const deniedJournal=await prepare({...options,db:retryDb},storage);
await assert.rejects(deniedJournal.submit());
assert.equal(deniedJournal.canDiscard(),true);
assert.equal(records.size,0,'definitive rejection must not strand recovery after reload');
deniedJournal.discard(); assert.equal(records.size,0);
loseResponse=false;
await prepare(options,storage); // Reserved before a request that never reached the server.
const notCommitted=restore(options,storage);
const beforeRetry=calls.length;
assert.equal((await notCommitted.submit(options.text)).question,options.text);
assert.equal(calls.length,beforeRetry+2,'same-key write plus exact readback');
assert.equal(calls[beforeRetry].p_request_id,'request-fixed');
assert.equal(records.size,0);
await assert.rejects(prepare(options,{...storage,setItem:()=>{throw new Error('STORAGE_BLOCKED');}}),/STORAGE_BLOCKED/);
assert.equal(records.size,0);
storage.setItem('cnyos.clarification.pending.v1:pharmacy:order','{}');
assert.throws(()=>restore(options,storage),/INVALID_RECOVERY/);
assert.equal(records.size,1,'malformed marker must not be silently deleted');
console.log('Clarification journal passed: metadata-only marker, read-only reload recovery, same-key exact-text retry, prior uncertainty, actor/order isolation and storage fail-closed.');
