import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const values=new Map();
const storage={get length(){return values.size;},key:index=>[...values.keys()][index]??null,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};
const sandbox={window:{},crypto:webcrypto,TextEncoder};
vm.runInNewContext(await fs.readFile(new URL('../replacement-action.js',import.meta.url),'utf8'),sandbox);
let receipt,writes=0;
const db={async rpc(_name,args){
  if(args.p_action==='replace') {
    writes++;
    receipt={request_id:args.p_request_id,ticket_id:args.p_ticket_id,old_order_id:'old',actor_id:'doctor',new_rx_id:'new-rx',new_order_id:'new-order',
      request_payload:{ticket:args.p_ticket_id,reason:args.p_reason,notes:args.p_notes,items:args.p_items}};
    throw new Error('Synthetic lost response');
  }
  return {data:receipt};
}};
const options={db,actorId:'doctor',ticketId:'ticket',oldOrderId:'old',reason:'Synthetic reason',notes:'Synthetic clinical text',items:[{product_id:'product',dose:'Synthetic dose'}],storage};
const first=await sandbox.window.CnyosReplacementAction.prepare(options);
await assert.rejects(first.submit(),/lost response/);
assert.equal(values.size,1);
assert.equal(sandbox.window.CnyosReplacementAction.hasPending({actorId:'doctor',storage}),true);
assert.equal(sandbox.window.CnyosReplacementAction.hasPending({actorId:'other',storage}),false);
assert.ok(![...values.values()][0].includes('Synthetic'));
await assert.rejects(sandbox.window.CnyosReplacementAction.prepare({...options,notes:'Changed'}),/PENDING_CONFLICT/);
const reopened=sandbox.window.CnyosReplacementAction.restore({db,actorId:'doctor',ticketId:'ticket',storage});
assert.equal(reopened.requestId,first.requestId);
await assert.rejects(reopened.submit(),/DRAFT_REQUIRED/);
const originalReceipt=receipt;
receipt={...receipt,actor_id:'someone-else'};
await assert.rejects(reopened.recover(),/READBACK_MISMATCH/);
assert.equal(values.size,1);
receipt={...originalReceipt,request_payload:{...originalReceipt.request_payload,notes:'tampered'}};
await assert.rejects(reopened.recover(),/READBACK_MISMATCH/);
assert.equal(values.size,1);
receipt=originalReceipt;
assert.equal((await reopened.recover()).new_order_id,'new-order');
assert.equal(values.size,0);
assert.equal(sandbox.window.CnyosReplacementAction.hasPending({actorId:'doctor',storage}),false);
assert.equal(writes,1);
await reopened.recover();
assert.equal(writes,1);
assert.equal(sandbox.window.CnyosReplacementAction.restore({db,actorId:'doctor',ticketId:'ticket',storage}),null);
for(const invalid of ['', '{',JSON.stringify({version:1}),JSON.stringify({version:1,actorId:'doctor',ticketId:'ticket',oldOrderId:'old',requestId:'key',digest:'a'.repeat(64),clinicalText:'must not be accepted'})]) {
  values.set('cnyos.replacement.pending.v1:doctor:ticket',invalid);
  assert.throws(()=>sandbox.window.CnyosReplacementAction.restore({db,actorId:'doctor',ticketId:'ticket',storage}),/PENDING_CONFLICT/);
  await assert.rejects(sandbox.window.CnyosReplacementAction.prepare(options),/PENDING_CONFLICT/);
  assert.equal(values.get('cnyos.replacement.pending.v1:doctor:ticket'),invalid);
}
values.clear();
let releaseRead;
const heldDb={rpc:()=>new Promise(resolve=>{releaseRead=resolve;})};
const held=await sandbox.window.CnyosReplacementAction.prepare({...options,db:heldDb});
const reading=held.recover();
await assert.rejects(held.recover(),/REQUEST_BUSY/);
const journalKey='cnyos.replacement.pending.v1:doctor:ticket';
values.set(journalKey,'changed while waiting');
releaseRead({data:{...originalReceipt,request_id:held.requestId}});
await assert.rejects(reading,/JOURNAL_CHANGED/);
assert.equal(values.get(journalKey),'changed while waiting');
values.clear();
await assert.rejects(sandbox.window.CnyosReplacementAction.prepare({...options,storage:{...storage,setItem(){throw new Error('Storage denied');}}}),/Storage denied/);
const rejectedDb={rpc:async()=>({error:{code:'P0001',message:'REPLACEMENT_REASON_REQUIRED'}})};
const rejected=await sandbox.window.CnyosReplacementAction.prepare({...options,db:rejectedDb});
await assert.rejects(rejected.submit());
assert.equal(rejected.canDiscard(),true);
rejected.discard();
assert.equal(values.size,0);
await assert.rejects(rejected.submit(),/DISCARDED/);
const unknown=await sandbox.window.CnyosReplacementAction.prepare({...options,db});
await assert.rejects(unknown.submit());
const resumed=await sandbox.window.CnyosReplacementAction.prepare({...options,db:rejectedDb});
await assert.rejects(resumed.submit());
assert.equal(resumed.canDiscard(),false,'a later rejection cannot erase earlier uncertainty');
assert.throws(()=>resumed.discard(),/OUTCOME_UNCERTAIN/);
assert.equal(values.size,1);
console.log('Replacement request controller passed: durable metadata-only identity, changed draft rejection, reload recovery after lost response, one write and storage failure before mutation.');
